### ISSUE TITLE
Where can I find the RT ChatGPT Assistant interface?

### ISSUE THREAD

**Issue by oushusheng** [frostschutz/MyBB-PluginLibrary#13]
I think I should send the file to the correct folder.
![68747470733a2f2f692e706f7374696d672e63632f6b67565a767146342f7373312e706e67](https://github.com/frostschutz/MyBB-PluginLibrary/assets/171921908/06dc433b-8d2a-4b92-a207-8b0abf79ea21)

**Comment by frostschutz** [comment]
I have no idea what this is so I can't help you there.
